"""Jordan hierarchy construction on operator space.

The hierarchy used here is generated by right-multiplication of a seed operator
by one-body generators and then orthogonal closure at each order.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np

from ..math import (
    devectorize,
    orth_columns,
    projector_from_basis,
    safe_matmul,
    vectorize,
)
from ..spaces import LabeledTensorSpace


class JordanFiltration:
    """Numerical cumulative hierarchy ``J_{<=j}`` and layers ``ΔJ_j``.

    Definitions in this implementation:
    - ``J_{<=0} = span{seed_operator}`` (default seed is identity),
    - ``J_{<=j}`` is generated from ``J_{<=j-1}`` by right-multiplying with
      one-body generators and orthonormalizing in Hilbert-Schmidt metric.

    If ``support_projector=Q`` is provided, all candidates are compressed to
    ``Q X Q`` so the hierarchy is local to a sector/multiplicity block.

    Notes
    -----
    This is a practical numerical realization for invariance checks rather than a
    symbolic PBW basis construction.
    """

    def __init__(
        self,
        space: LabeledTensorSpace,
        generator_list: Optional[Iterable[np.ndarray]] = None,
        seed_operator: Optional[np.ndarray] = None,
        support_projector: Optional[np.ndarray] = None,
    ):
        self.space = space
        self.dim = space.dim
        self.liou_dim = self.dim ** 2
        self.generator_list = list(space.generators.values()) if generator_list is None else list(generator_list)
        self.seed_operator = (
            np.eye(self.dim, dtype=complex) if seed_operator is None else np.asarray(seed_operator, dtype=complex)
        )
        self.support_projector = (
            None if support_projector is None else np.asarray(support_projector, dtype=complex)
        )

        self.cumulative_bases: Dict[int, np.ndarray] = {}
        self.layer_bases: Dict[int, np.ndarray] = {}
        self._projector_cumulative_cache: Dict[int, np.ndarray] = {}
        self._projector_layer_cache: Dict[int, np.ndarray] = {}

    def _clear_projector_cache(self) -> None:
        self._projector_cumulative_cache.clear()
        self._projector_layer_cache.clear()

    def _project_to_support(self, mats: np.ndarray) -> np.ndarray:
        if self.support_projector is None:
            return mats
        return np.einsum(
            "ab,kbc,cd->kad",
            self.support_projector,
            mats,
            self.support_projector,
            optimize=True,
        )

    def _candidate_columns(self, prev_basis: np.ndarray) -> List[np.ndarray]:
        if prev_basis.size == 0 or len(self.generator_list) == 0:
            return []

        n_prev = prev_basis.shape[1]
        prev_mats = prev_basis.T.reshape(n_prev, self.dim, self.dim)
        out: List[np.ndarray] = []

        for G in self.generator_list:
            # Batched right multiplication of all basis elements by one generator.
            products = np.einsum("kij,jl->kil", prev_mats, G, optimize=True)
            products = self._project_to_support(products)
            out.append(products.reshape(n_prev, self.liou_dim).T)
        return out

    def build(self, max_order: int) -> None:
        """Build hierarchy bases up to order ``max_order``."""
        self.cumulative_bases.clear()
        self.layer_bases.clear()
        self._clear_projector_cache()

        seed = self.seed_operator
        if self.support_projector is not None:
            seed = safe_matmul(self.support_projector, seed, self.support_projector)

        cum_basis = orth_columns(vectorize(seed))
        self.cumulative_bases[0] = cum_basis
        self.layer_bases[0] = cum_basis

        for j in range(1, max_order + 1):
            prev_basis = self.cumulative_bases[j - 1]
            candidates = [prev_basis]
            candidates.extend(self._candidate_columns(prev_basis))

            big = np.column_stack(candidates)
            new_cum = orth_columns(big)
            self.cumulative_bases[j] = new_cum

            P_prev = self.projector_cumulative(j - 1)
            residual = new_cum - safe_matmul(P_prev, new_cum)
            self.layer_bases[j] = orth_columns(residual)

    def projector_cumulative(self, j: int) -> np.ndarray:
        """Return orthogonal projector onto cumulative subspace ``J_{<=j}``."""
        if j not in self._projector_cumulative_cache:
            self._projector_cumulative_cache[j] = projector_from_basis(self.cumulative_bases[j])
        return self._projector_cumulative_cache[j]

    def projector_layer(self, j: int) -> np.ndarray:
        """Return orthogonal projector onto exact layer ``Delta J_j``."""
        if j not in self._projector_layer_cache:
            self._projector_layer_cache[j] = projector_from_basis(self.layer_bases[j])
        return self._projector_layer_cache[j]

    @staticmethod
    def _apply_basis_projection(v: np.ndarray, basis: np.ndarray) -> np.ndarray:
        if basis.size == 0:
            return np.zeros_like(v)
        coeff = safe_matmul(basis.conj().T, v)
        return safe_matmul(basis, coeff)

    def apply_projector_cumulative(self, rho: np.ndarray, j: int) -> np.ndarray:
        """Apply cumulative projector to an operator in matrix form."""
        v = vectorize(rho)
        proj_v = self._apply_basis_projection(v, self.cumulative_bases[j])
        return devectorize(proj_v, self.dim)

    def apply_projector_layer(self, rho: np.ndarray, j: int) -> np.ndarray:
        """Apply exact-layer projector to an operator in matrix form."""
        v = vectorize(rho)
        proj_v = self._apply_basis_projection(v, self.layer_bases[j])
        return devectorize(proj_v, self.dim)

    def cumulative_weight(self, rho: np.ndarray, j: int) -> float:
        """Return squared HS-norm of cumulative projection at order ``j``."""
        v = vectorize(rho)
        basis = self.cumulative_bases[j]
        coeff = safe_matmul(basis.conj().T, v)
        return float(np.real(np.vdot(coeff, coeff)))

    def layer_weight(self, rho: np.ndarray, j: int) -> float:
        """Return squared HS-norm of exact-layer projection at order ``j``."""
        v = vectorize(rho)
        basis = self.layer_bases[j]
        coeff = safe_matmul(basis.conj().T, v)
        return float(np.real(np.vdot(coeff, coeff)))

    def dimensions_summary(self, max_order: int) -> List[Tuple[int, int, int]]:
        """Return ``(order, dim cumulative, dim layer)`` entries."""
        out = []
        for j in range(max_order + 1):
            out.append((j, self.cumulative_bases[j].shape[1], self.layer_bases[j].shape[1]))
        return out
