"""Passive linear-optics dynamics on external tensor space."""

from __future__ import annotations

import numpy as np

from .math import haar_random_unitary, safe_matmul
from .spaces import LabeledTensorSpace


class PassiveLODynamics:
    """Unitary channel generated by single-particle interferometers.

    For single-particle unitary ``S``, the labeled ``n``-particle action is
    ``U = S^{\\otimes n}``, and density evolution is ``rho -> U rho U^†``.
    """

    def __init__(self, space: LabeledTensorSpace):
        self.space = space

    def random_single_particle_unitary(self, rng: np.random.Generator) -> np.ndarray:
        """Sample Haar-random single-particle unitary matrix."""
        return haar_random_unitary(self.space.m, rng)

    def evolve_density(self, rho: np.ndarray, S: np.ndarray) -> np.ndarray:
        """Evolve density operator as ``rho -> U rho U^†`` with ``U=S^{\\otimes n}``."""
        U = self.space.total_unitary_from_single_particle(S)
        return safe_matmul(U, rho, U.conj().T)

    def heisenberg_conjugate(self, X: np.ndarray, S: np.ndarray) -> np.ndarray:
        """Heisenberg conjugation ``X -> U X U^†`` with ``U=S^{\\otimes n}``."""
        U = self.space.total_unitary_from_single_particle(S)
        return safe_matmul(U, X, U.conj().T)
